### ISSUE TITLE
getting ip address

### ISSUE THREAD

**Issue by Danysevian** [hxrofo/hotspotphisher#1]
when i try to connect to the hotspot it gets stuck getting ip address and won't connect. please can somebody help me?

**Comment by GuilhermeWalisson** [comment]
@Danysevian Did you manage to solve the problem?

**Comment by hxrofo** [comment]
check version 2 of the script

**Comment by hxrofo** [comment]
check version 2 of the script, and if you still have problems, remember that it's only a bash script to automate commands. open the script and play with the parameters until you fix the problem. I'm a total beginner just like you.

**Comment by GuilhermeWalisson** [comment]
@hxrofo Although I didn't use KaliNethunter, I used termux (because it was a more viable option for me, even with root).  But, it worked, using another bash script, which does the internal poisoning, redirecting the user who connects to the Hotspot, however, I used the sites in your repository, I just ran on port 8080, and that's it. 
![Screenshot_2023-06-18-21-19-37-779_com termux](https://github.com/hxrofo/hotspotphisher/assets/67160639/2fe4a279-a915-4b66-8d5d-d38574297140)
